// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_aggregates.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDailyAggregates = `-- name: DeleteDailyAggregates :exec
DELETE FROM daily_aggregates
WHERE user_id = $1::uuid
  AND local_date BETWEEN $2::date AND $3::date
`

type DeleteDailyAggregatesParams struct {
	UserID        uuid.UUID
	FromLocalDate time.Time
	ToLocalDate   time.Time
}

func (q *Queries) DeleteDailyAggregates(ctx context.Context, arg DeleteDailyAggregatesParams) error {
	_, err := q.db.Exec(ctx, deleteDailyAggregates, arg.UserID, arg.FromLocalDate, arg.ToLocalDate)
	return err
}

const insertDailyAggregates = `-- name: InsertDailyAggregates :execrows
WITH per_source AS (
  SELECT
    metric,
    (start_at AT TIME ZONE $2::text)::date AS local_date,
    source,
    min(value) AS min_value,
    max(value) AS max_value,
    sum(value) AS sum_value,
    count(*) AS sample_count
  FROM health_samples
  WHERE user_id = $1::uuid
    AND start_at >= ($3::date::timestamp AT TIME ZONE $2::text)
    AND start_at < (($4::date + 1)::timestamp AT TIME ZONE $2::text)
  GROUP BY metric, local_date, source
),
busiest_source AS (
  SELECT DISTINCT ON (metric, local_date) metric, local_date, min_value, max_value, sum_value, sample_count
  FROM per_source
  WHERE metric = ANY($5::text[])
  ORDER BY metric, local_date, sum_value DESC, source
),
every_source AS (
  SELECT metric, local_date, min(min_value) AS min_value, max(max_value) AS max_value,
    sum(sum_value) AS sum_value, sum(sample_count) AS sample_count
  FROM per_source
  WHERE NOT (metric = ANY($5::text[]))
  GROUP BY metric, local_date
)
INSERT INTO daily_aggregates (user_id, local_date, metric, min_value, avg_value, max_value, sum_value, sample_count)
SELECT $1::uuid, local_date, metric, min_value, sum_value / sample_count, max_value, sum_value, sample_count
FROM (SELECT metric, local_date, min_value, max_value, sum_value, sample_count FROM busiest_source UNION ALL SELECT metric, local_date, min_value, max_value, sum_value, sample_count FROM every_source) AS chosen
`

type InsertDailyAggregatesParams struct {
	UserID            uuid.UUID
	TimeZone          string
	FromLocalDate     time.Time
	ToLocalDate       time.Time
	CumulativeMetrics []string
}

func (q *Queries) InsertDailyAggregates(ctx context.Context, arg InsertDailyAggregatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDailyAggregates,
		arg.UserID,
		arg.TimeZone,
		arg.FromLocalDate,
		arg.ToLocalDate,
		arg.CumulativeMetrics,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDailyAggregates = `-- name: ListDailyAggregates :many
SELECT local_date, metric, avg_value, sum_value
FROM daily_aggregates
WHERE user_id = $1::uuid
  AND local_date BETWEEN $2::date AND $3::date
  AND metric = ANY($4::text[])
ORDER BY local_date, metric
`

type ListDailyAggregatesParams struct {
	UserID        uuid.UUID
	FromLocalDate time.Time
	ToLocalDate   time.Time
	Metrics       []string
}

type ListDailyAggregatesRow struct {
	LocalDate time.Time
	Metric    string
	AvgValue  float64
	SumValue  float64
}

func (q *Queries) ListDailyAggregates(ctx context.Context, arg ListDailyAggregatesParams) ([]ListDailyAggregatesRow, error) {
	rows, err := q.db.Query(ctx, listDailyAggregates,
		arg.UserID,
		arg.FromLocalDate,
		arg.ToLocalDate,
		arg.Metrics,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyAggregatesRow
	for rows.Next() {
		var i ListDailyAggregatesRow
		if err := rows.Scan(
			&i.LocalDate,
			&i.Metric,
			&i.AvgValue,
			&i.SumValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
