// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: derived_metrics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBaselines = `-- name: DeleteBaselines :exec
DELETE FROM baselines
WHERE user_id = $1::uuid
  AND local_date BETWEEN $2::date AND $3::date
`

type DeleteBaselinesParams struct {
	UserID        uuid.UUID
	FromLocalDate time.Time
	ToLocalDate   time.Time
}

func (q *Queries) DeleteBaselines(ctx context.Context, arg DeleteBaselinesParams) error {
	_, err := q.db.Exec(ctx, deleteBaselines, arg.UserID, arg.FromLocalDate, arg.ToLocalDate)
	return err
}

const insertAnomalies = `-- name: InsertAnomalies :many
INSERT INTO anomalies (user_id, local_date, metric, z_score, direction)
SELECT $1::uuid, rows.local_date, rows.metric, rows.z_score, rows.direction
FROM jsonb_to_recordset($2::jsonb)
  AS rows (local_date date, metric text, z_score double precision, direction text)
ON CONFLICT (user_id, local_date, metric) DO NOTHING
RETURNING id, local_date, metric, z_score, direction
`

type InsertAnomaliesParams struct {
	UserID      uuid.UUID
	AnomalyRows []byte
}

type InsertAnomaliesRow struct {
	ID        uuid.UUID
	LocalDate time.Time
	Metric    string
	ZScore    float64
	Direction string
}

func (q *Queries) InsertAnomalies(ctx context.Context, arg InsertAnomaliesParams) ([]InsertAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, insertAnomalies, arg.UserID, arg.AnomalyRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertAnomaliesRow
	for rows.Next() {
		var i InsertAnomaliesRow
		if err := rows.Scan(
			&i.ID,
			&i.LocalDate,
			&i.Metric,
			&i.ZScore,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBaselines = `-- name: InsertBaselines :exec
INSERT INTO baselines (user_id, local_date, metric, mean, stddev, day_count)
SELECT $1::uuid, rows.local_date, rows.metric, rows.mean, rows.stddev, rows.day_count
FROM jsonb_to_recordset($2::jsonb)
  AS rows (local_date date, metric text, mean double precision, stddev double precision, day_count integer)
`

type InsertBaselinesParams struct {
	UserID       uuid.UUID
	BaselineRows []byte
}

func (q *Queries) InsertBaselines(ctx context.Context, arg InsertBaselinesParams) error {
	_, err := q.db.Exec(ctx, insertBaselines, arg.UserID, arg.BaselineRows)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (user_id, topic, payload)
VALUES ($1::uuid, $2::text, $3::jsonb)
`

type InsertOutboxEventParams struct {
	UserID  uuid.UUID
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.UserID, arg.Topic, arg.Payload)
	return err
}

const upsertDailyScores = `-- name: UpsertDailyScores :execrows
INSERT INTO daily_scores (user_id, local_date, sleep_score, recovery_score, activity_score, inputs, algorithm_version)
SELECT $1::uuid, rows.local_date, rows.sleep_score, rows.recovery_score, rows.activity_score,
  rows.inputs, $2::integer
FROM jsonb_to_recordset($3::jsonb)
  AS rows (local_date date, sleep_score smallint, recovery_score smallint, activity_score smallint, inputs jsonb)
ON CONFLICT (user_id, local_date) DO UPDATE
SET sleep_score = excluded.sleep_score, recovery_score = excluded.recovery_score,
  activity_score = excluded.activity_score, inputs = excluded.inputs,
  algorithm_version = excluded.algorithm_version, computed_at = now()
WHERE (daily_scores.sleep_score, daily_scores.recovery_score, daily_scores.activity_score,
    daily_scores.inputs, daily_scores.algorithm_version)
  IS DISTINCT FROM (excluded.sleep_score, excluded.recovery_score, excluded.activity_score,
    excluded.inputs, excluded.algorithm_version)
`

type UpsertDailyScoresParams struct {
	UserID           uuid.UUID
	AlgorithmVersion int32
	ScoreRows        []byte
}

func (q *Queries) UpsertDailyScores(ctx context.Context, arg UpsertDailyScoresParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDailyScores, arg.UserID, arg.AlgorithmVersion, arg.ScoreRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
