// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_samples.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dropHealthSamplesPartitionsBefore = `-- name: DropHealthSamplesPartitionsBefore :one
SELECT drop_health_samples_partitions_before($1::timestamptz)::integer AS dropped_count
`

func (q *Queries) DropHealthSamplesPartitionsBefore(ctx context.Context, cutoff time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, dropHealthSamplesPartitionsBefore, cutoff)
	var dropped_count int32
	err := row.Scan(&dropped_count)
	return dropped_count, err
}

const ensureHealthSamplesPartition = `-- name: EnsureHealthSamplesPartition :exec
SELECT ensure_health_samples_partition($1::timestamptz)
`

func (q *Queries) EnsureHealthSamplesPartition(ctx context.Context, sampleStartAt time.Time) error {
	_, err := q.db.Exec(ctx, ensureHealthSamplesPartition, sampleStartAt)
	return err
}

const upsertHealthSamples = `-- name: UpsertHealthSamples :execrows
INSERT INTO health_samples (user_id, metric, external_uuid, start_at, end_at, value, unit, source)
SELECT
  $1::uuid,
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::timestamptz[]),
  unnest($5::timestamptz[]),
  unnest($6::double precision[]),
  unnest($7::text[]),
  unnest($8::text[])
ON CONFLICT (user_id, metric, external_uuid, start_at) DO UPDATE
SET end_at = excluded.end_at, value = excluded.value, unit = excluded.unit, source = excluded.source
WHERE (health_samples.end_at, health_samples.value, health_samples.unit, health_samples.source)
  IS DISTINCT FROM (excluded.end_at, excluded.value, excluded.unit, excluded.source)
`

type UpsertHealthSamplesParams struct {
	UserID        uuid.UUID
	Metrics       []string
	ExternalUuids []string
	StartAts      []time.Time
	EndAts        []time.Time
	SampleValues  []float64
	Units         []string
	Sources       []string
}

func (q *Queries) UpsertHealthSamples(ctx context.Context, arg UpsertHealthSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertHealthSamples,
		arg.UserID,
		arg.Metrics,
		arg.ExternalUuids,
		arg.StartAts,
		arg.EndAts,
		arg.SampleValues,
		arg.Units,
		arg.Sources,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
