// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics_recompute_queue.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deferMetricsRecompute = `-- name: DeferMetricsRecompute :exec
UPDATE metrics_recompute_queue SET requested_at = now() WHERE user_id = $1::uuid
`

func (q *Queries) DeferMetricsRecompute(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deferMetricsRecompute, userID)
	return err
}

const findUserTimeZone = `-- name: FindUserTimeZone :one
SELECT timezone FROM users WHERE id = $1::uuid FOR KEY SHARE
`

func (q *Queries) FindUserTimeZone(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, findUserTimeZone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const finishMetricsRecompute = `-- name: FinishMetricsRecompute :exec
DELETE FROM metrics_recompute_queue
WHERE user_id = $1::uuid AND generation = $2::bigint
`

type FinishMetricsRecomputeParams struct {
	UserID     uuid.UUID
	Generation int64
}

func (q *Queries) FinishMetricsRecompute(ctx context.Context, arg FinishMetricsRecomputeParams) error {
	_, err := q.db.Exec(ctx, finishMetricsRecompute, arg.UserID, arg.Generation)
	return err
}

const listUsersDueForRecompute = `-- name: ListUsersDueForRecompute :many
SELECT user_id, from_local_date, generation
FROM metrics_recompute_queue
WHERE requested_at <= now() - make_interval(secs => $1::integer)
ORDER BY requested_at
LIMIT $2::integer
`

type ListUsersDueForRecomputeParams struct {
	SettleSeconds int32
	UserLimit     int32
}

type ListUsersDueForRecomputeRow struct {
	UserID        uuid.UUID
	FromLocalDate time.Time
	Generation    int64
}

func (q *Queries) ListUsersDueForRecompute(ctx context.Context, arg ListUsersDueForRecomputeParams) ([]ListUsersDueForRecomputeRow, error) {
	rows, err := q.db.Query(ctx, listUsersDueForRecompute, arg.SettleSeconds, arg.UserLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersDueForRecomputeRow
	for rows.Next() {
		var i ListUsersDueForRecomputeRow
		if err := rows.Scan(&i.UserID, &i.FromLocalDate, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMetricsStale = `-- name: MarkMetricsStale :exec
INSERT INTO metrics_recompute_queue (user_id, from_local_date)
SELECT users.id, ($1::timestamptz AT TIME ZONE users.timezone)::date
FROM users
WHERE users.id = $2::uuid
ON CONFLICT (user_id) DO UPDATE
SET from_local_date = LEAST(metrics_recompute_queue.from_local_date, excluded.from_local_date),
  generation = metrics_recompute_queue.generation + 1,
  requested_at = now()
`

type MarkMetricsStaleParams struct {
	EarliestChangedAt time.Time
	UserID            uuid.UUID
}

func (q *Queries) MarkMetricsStale(ctx context.Context, arg MarkMetricsStaleParams) error {
	_, err := q.db.Exec(ctx, markMetricsStale, arg.EarliestChangedAt, arg.UserID)
	return err
}

const tryLockUserMetrics = `-- name: TryLockUserMetrics :one
SELECT pg_try_advisory_xact_lock(hashtext('metrics_recompute'), hashtext($1::uuid::text)) AS locked
`

func (q *Queries) TryLockUserMetrics(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockUserMetrics, userID)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
