// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Consent struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Kind       string
	Version    string
	AcceptedAt time.Time
}

type HealthSample struct {
	UserID       uuid.UUID
	Metric       string
	ExternalUuid string
	StartAt      time.Time
	EndAt        time.Time
	Value        float64
	Unit         string
	Source       string
}

type SleepSession struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ExternalUuid string
	StartAt      time.Time
	EndAt        time.Time
	Source       string
	Stages       []byte
}

type User struct {
	ID          uuid.UUID
	ClerkUserID string
	Timezone    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
