// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sleep_sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listSleepSessionsEndingBetween = `-- name: ListSleepSessionsEndingBetween :many
SELECT start_at, end_at, stages
FROM sleep_sessions
WHERE user_id = $1::uuid
  AND end_at >= ($3::date::timestamp AT TIME ZONE $2::text)
  AND end_at < (($4::date + 1)::timestamp AT TIME ZONE $2::text)
ORDER BY end_at
`

type ListSleepSessionsEndingBetweenParams struct {
	UserID        uuid.UUID
	TimeZone      string
	FromLocalDate time.Time
	ToLocalDate   time.Time
}

type ListSleepSessionsEndingBetweenRow struct {
	StartAt time.Time
	EndAt   time.Time
	Stages  []byte
}

func (q *Queries) ListSleepSessionsEndingBetween(ctx context.Context, arg ListSleepSessionsEndingBetweenParams) ([]ListSleepSessionsEndingBetweenRow, error) {
	rows, err := q.db.Query(ctx, listSleepSessionsEndingBetween,
		arg.UserID,
		arg.TimeZone,
		arg.FromLocalDate,
		arg.ToLocalDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSleepSessionsEndingBetweenRow
	for rows.Next() {
		var i ListSleepSessionsEndingBetweenRow
		if err := rows.Scan(&i.StartAt, &i.EndAt, &i.Stages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSleepSessions = `-- name: UpsertSleepSessions :execrows
INSERT INTO sleep_sessions (user_id, external_uuid, start_at, end_at, source, stages)
SELECT
  $1::uuid,
  unnest($2::text[]),
  unnest($3::timestamptz[]),
  unnest($4::timestamptz[]),
  unnest($5::text[]),
  unnest($6::jsonb[])
ON CONFLICT (user_id, external_uuid) DO UPDATE
SET start_at = excluded.start_at, end_at = excluded.end_at, source = excluded.source, stages = excluded.stages
WHERE (sleep_sessions.start_at, sleep_sessions.end_at, sleep_sessions.source, sleep_sessions.stages)
  IS DISTINCT FROM (excluded.start_at, excluded.end_at, excluded.source, excluded.stages)
`

type UpsertSleepSessionsParams struct {
	UserID        uuid.UUID
	ExternalUuids []string
	StartAts      []time.Time
	EndAts        []time.Time
	Sources       []string
	Stages        [][]byte
}

func (q *Queries) UpsertSleepSessions(ctx context.Context, arg UpsertSleepSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSleepSessions,
		arg.UserID,
		arg.ExternalUuids,
		arg.StartAts,
		arg.EndAts,
		arg.Sources,
		arg.Stages,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
