// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const findUserIDWithHealthDataConsent = `-- name: FindUserIDWithHealthDataConsent :one
SELECT users.id FROM users
WHERE users.clerk_user_id = $1
  AND EXISTS (
    SELECT 1 FROM consents
    WHERE consents.user_id = users.id AND consents.kind = 'health_data_processing'
  )
`

func (q *Queries) FindUserIDWithHealthDataConsent(ctx context.Context, clerkUserID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findUserIDWithHealthDataConsent, clerkUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
