// Why: copies each metric's canonical unit from @wearwise/metrics-catalog into Go, so ingest validates against the one catalog.
// Must not: emit anything beyond the unit map; metrics are only ever defined in packages/metrics-catalog.
import { writeFileSync } from "node:fs";
import { metricCatalog } from "@wearwise/metrics-catalog";

const outputPath = process.argv[2];
if (outputPath === undefined) {
  throw new Error("usage: node generate-units.ts <output.go>");
}
const unitEntries = metricCatalog
  .map(
    (metric) =>
      `\t${JSON.stringify(metric.id)}: ${JSON.stringify(metric.unit)},`,
  )
  .join("\n");
writeFileSync(
  outputPath,
  `// Code generated by generate-units.ts from @wearwise/metrics-catalog. DO NOT EDIT.\n\npackage metriccatalog\n\nvar canonicalUnits = map[string]string{\n${unitEntries}\n}\n`,
);
