// Code generated by generate-units.ts from @wearwise/metrics-catalog. DO NOT EDIT.

package metriccatalog

var canonicalUnits = map[string]string{
	"exercise_time":                "min",
	"walking_speed":                "km/h",
	"stand_hours":                  "count",
	"stand_time":                   "min",
	"step_count":                   "count",
	"walking_running_distance":     "km",
	"flights_climbed":              "count",
	"active_energy":                "kcal",
	"physical_effort":              "kcal/hr·kg",
	"heart_rate":                   "bpm",
	"resting_heart_rate":           "bpm",
	"walking_heart_rate_average":   "bpm",
	"heart_rate_variability":       "ms",
	"respiratory_rate":             "breaths/min",
	"blood_oxygen_saturation":      "%",
	"sleep_analysis":               "hr",
	"basal_energy":                 "kcal",
	"sleeping_wrist_temperature":   "degC",
	"time_in_daylight":             "min",
	"environmental_audio_exposure": "dBASPL",
	"headphone_audio_exposure":     "dBASPL",
}
